services:
  - type: web
    name: photo-poetry-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGINS
        value: https://photo-poetry-app.netlify.app
      - key: GOOGLE_CLOUD_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false